# Generated by Django 5.2.7 on 2025-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
