# Generated by Django 5.2.8 on 2025-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='id_coche',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coche',
            name='id_usuario',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
