# Generated by Django 5.2.8 on 2025-11-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_coche_id_coche_coche_id_usuario_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
